import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase'
import { generateReferenceCode } from '@/lib/utils'
import { createRouteHandlerClient } from '@/lib/supabase-server'
import { cookies } from 'next/headers'
import { sendOrderSuccessEmail, sendAdminNewOrderAlert } from '@/lib/email-service'
import { sendOrderSuccessSMS, sendAdminAgentOrderAlert } from '@/lib/sms-service'
import { sendPushToUser, sendPushToAdmins } from '@/lib/web-push'
import { Ratelimit } from '@upstash/ratelimit'
import { Redis } from '@upstash/redis'

const purchaseRateLimit = new Ratelimit({
    redis: Redis.fromEnv(),
    limiter: Ratelimit.slidingWindow(3, '10 s'),
    prefix: 'rl:purchase',
})

export async function POST(request: NextRequest) {
    try {
        const cookieStore = await cookies()
        const supabaseUserClient = await createRouteHandlerClient()
        const { data: { user: authUser }, error: authError } = await supabaseUserClient.auth.getUser()

        if (authError || !authUser) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const user = authUser
        const userId = user.id

        let rateLimitOk = true;
        try {
            const rlResult = await purchaseRateLimit.limit(userId)
            rateLimitOk = rlResult.success
        } catch (rlError) {
            console.error('[Purchase] Rate limit error, bypassing:', rlError)
        }
        
        if (!rateLimitOk) {
            return NextResponse.json({ error: 'Too many requests. Please wait.' }, { status: 429 })
        }

        let body: any;
        try {
            body = await request.json()
        } catch (e) {
            return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
        }

        // referenceCode is now generated by the frontend to act as an idempotency key.
        // If the same referenceCode is submitted twice, the second request will fail on
        // the unique constraint, preventing double orders.
        const { packageId, phoneNumber, referenceCode: clientReferenceCode } = body

        if (!phoneNumber || typeof phoneNumber !== 'string') {
            return NextResponse.json({ error: 'Phone number is required' }, { status: 400 })
        }

        const cleanPhone = phoneNumber.replace(/\s+/g, '')
        const ghanaPhoneRegex = /^(0\d{9}|233\d{9})$/

        if (!ghanaPhoneRegex.test(cleanPhone)) {
            return NextResponse.json({
                error: 'Invalid phone number format. Use Ghana format: 0XXXXXXXXX or 233XXXXXXXXX'
            }, { status: 400 })
        }

        // Service role client for privileged operations
        const supabase = createServerClient()

        // === IDEMPOTENCY: If a referenceCode was provided by the client, check for duplicates first ===
        if (clientReferenceCode) {
            const { data: existingOrder } = await (supabase.from('orders') as any)
                .select('id, reference_code, status')
                .eq('reference_code', clientReferenceCode)
                .maybeSingle()

            if (existingOrder) {
                // Order already exists — this is a duplicate request. Return success with existing data.
                console.log('[Purchase] Duplicate request blocked for client reference')
                return NextResponse.json({
                    success: true,
                    isDuplicate: true,
                    order: {
                        id: existingOrder.id,
                        reference_code: existingOrder.reference_code,
                        status: existingOrder.status,
                    },
                })
            }
        }

        // Get package details
        const { data: pkg, error: pkgError } = await supabase
            .from('data_packages')
            .select('*')
            .eq('id', packageId)
            .eq('is_available', true)
            .single()

        if (pkgError || !pkg) {
            return NextResponse.json({ error: 'Package not found' }, { status: 404 })
        }

        // Check if phone is blacklisted
        const { data: blacklisted } = await supabase
            .from('phone_blacklist')
            .select('id')
            .eq('phone_number', phoneNumber)
            .single()

        if (blacklisted) {
            return NextResponse.json({ error: 'This phone number is not allowed' }, { status: 400 })
        }

        // Get user role + sub-agent status for price calculation
        const { data: userRoleData } = await supabase
            .from('users')
            .select('role, agent_expires_at, dealer_expires_at')
            .eq('id', userId)
            .single()

        const userRole = (userRoleData as any)?.role
        const agentExpiresAt = (userRoleData as any)?.agent_expires_at
        const dealerExpiresAt = (userRoleData as any)?.dealer_expires_at
        const isAgent = userRole === 'agent'
        const isDealer = userRole === 'dealer'

        // Check if user is a sub-agent
        const { data: subAgentData } = await supabase
            .from('sub_agents')
            .select('id, status, upline_shop_id')
            .eq('user_id', userId)
            .single()

        // If user is a sub-agent, apply sub-pricing logic
        let priceToCharge = (pkg as any).price
        let isSub = false
        let uplineShopId: string | null = null

        if (subAgentData) {
            isSub = true
            uplineShopId = subAgentData.upline_shop_id

            // Eligibility gate: sub must be active + upline must be eligible
            if (subAgentData.status !== 'active') {
                return NextResponse.json(
                    { error: 'Your sub-agent account is not active' },
                    { status: 403 }
                )
            }

            // Check upline eligibility (live evaluation, never cached)
            const { data: uplineOwner } = await supabase
                .from('shop_profiles')
                .select('owner_id')
                .eq('id', uplineShopId)
                .single()

            if (uplineOwner) {
                const { data: uplineUserData } = await supabase
                    .from('users')
                    .select('role, agent_expires_at, dealer_expires_at')
                    .eq('id', uplineOwner.owner_id)
                    .single()

                const uplineRole = (uplineUserData as any)?.role
                const uplineAgentExpiresAt = (uplineUserData as any)?.agent_expires_at
                const uplineDealerExpiresAt = (uplineUserData as any)?.dealer_expires_at
                const now = new Date()

                // Eligibility: (role='agent' AND agent_expires_at IS NULL) OR (role='dealer' AND dealer_expires_at > now())
                const isUplineEligible =
                    (uplineRole === 'agent' && !uplineAgentExpiresAt) ||
                    (uplineRole === 'dealer' && uplineDealerExpiresAt && new Date(uplineDealerExpiresAt) > now)

                if (!isUplineEligible) {
                    return NextResponse.json(
                        { error: 'Your upline Lead is no longer eligible to operate. Please contact support.' },
                        { status: 403 }
                    )
                }
            }

            // Get sub_price from upline's pricing for this package
            const { data: subPricingData } = await supabase
                .from('shop_pricing')
                .select('sub_price')
                .eq('shop_id', uplineShopId)
                .eq('package_id', packageId)
                .single()

            if (!subPricingData || !subPricingData.sub_price) {
                return NextResponse.json(
                    { error: 'This package is not yet available for sub-agents' },
                    { status: 400 }
                )
            }

            priceToCharge = subPricingData.sub_price
        } else {
            // Regular user: apply role-based pricing (existing logic)
            priceToCharge = (isDealer && (pkg as any).dealer_price > 0)
                ? (pkg as any).dealer_price
                : (isAgent && (pkg as any).agent_price > 0)
                    ? (pkg as any).agent_price
                    : (pkg as any).price
        }

        // === SECURITY: Atomic wallet deduction (prevents double-spend) ===
        const { data: deductResult, error: deductError } = await (supabase as any)
            .rpc('deduct_wallet_balance', {
                p_user_id: userId,
                p_amount: priceToCharge,
            })

        if (deductError) {
            if (deductError.message?.includes('INSUFFICIENT_BALANCE')) {
                return NextResponse.json({ error: 'Insufficient balance' }, { status: 400 })
            }
            console.error('Wallet deduction error:', deductError)
            return NextResponse.json({ error: 'Failed to process payment' }, { status: 500 })
        }

        const walletRow = deductResult?.[0] || deductResult
        const walletId = walletRow?.wallet_id
        const newBalance = walletRow?.new_balance

        if (!walletId) {
            return NextResponse.json({ error: 'Wallet not found' }, { status: 404 })
        }

        // Use client-provided referenceCode if available, else generate a new one
        const referenceCode = clientReferenceCode || generateReferenceCode()

        // Create order AFTER successful deduction
        const { data: order, error: orderError } = await (supabase
            .from('orders') as any)
            .insert({
                user_id: userId,
                phone_number: phoneNumber,
                network: (pkg as any).network,
                size: (pkg as any).size,
                price: priceToCharge,
                cost_price_at_time: (pkg as any).cost_price || 0,
                role_at_time: (userRoleData as any)?.role || 'customer',
                status: 'pending',
                payment_status: 'paid',
                reference_code: referenceCode,
                fulfillment_method: 'auto',
            })
            .select()
            .single()

        if (orderError) {
            console.error('Order creation error:', orderError)
            // Refund the deducted amount atomically since order failed
            const { error: refundError } = await (supabase as any)
                .rpc('credit_wallet_balance', {
                    p_user_id: userId,
                    p_amount: priceToCharge
                })

            if (refundError) {
                console.error('CRITICAL: Refund RPC failed', refundError)
            }
            return NextResponse.json({ error: 'Failed to create order' }, { status: 500 })
        }

        // === PERFORMANCE: Create wallet transaction (non-blocking, fire-and-forget) ===
        ;(supabase.from('wallet_transactions') as any).insert({
            wallet_id: walletId,
            user_id: userId,
            type: 'debit',
            amount: priceToCharge,
            description: `Data purchase: ${(pkg as any).size} for ${phoneNumber}`,
            reference: referenceCode,
            source: 'purchase',
            status: 'completed',
        }).then(() => {}).catch((e: any) => console.error('[Purchase] Tx insert error:', e))

        // === PERFORMANCE: Create notification + web push (fire-and-forget) ===
        ;(supabase.from('notifications') as any).insert({
            user_id: userId,
            title: 'Order Placed',
            message: `Your order for ${(pkg as any).size} to ${phoneNumber} has been placed and is being processed.`,
            type: 'order_update',
            action_url: `/dashboard/my-orders`,
        }).then(() => {}).catch((e: any) => console.error('[Purchase] Notification error:', e))

        await sendPushToUser(userId, {
            title: 'Order Placed',
            body: `Your ${(pkg as any).size} bundle for ${phoneNumber} is being processed.`,
            url: '/dashboard/my-orders',
        }).catch((e: any) => console.error('[Purchase] Push error:', e))

        // === NOTIFICATIONS & AUTO-FULFILLMENT: Awaited to ensure Vercel doesn't kill process ===
        try {
            // Fetch user data once for both notifications and fulfillment
            const { data: userData, error: userFetchError } = await supabase
                .from('users')
                .select('email, first_name, last_name, phone_number, role')
                .eq('id', userId)
                .single()

            if (userFetchError || !userData) {
                console.error('[Purchase] Post-purchase user fetch failed:', userFetchError)
            } else {
                const userEmail = (userData as any).email
                const firstName = (userData as any).first_name || 'Customer'
                const accountHolderPhone = (userData as any).phone_number

                // 1. Send User Email Confirmation (Removed as requested)
                // if (userEmail) {
                //     await sendOrderSuccessEmail(userEmail, firstName, {
                //         referenceCode,
                //         phoneNumber,
                //         network: (pkg as any).network,
                //         size: (pkg as any).size,
                //         price: priceToCharge
                //     }).then(() => console.log('[Purchase] Confirmation email sent successfully'))
                //       .catch((err: Error) => console.error('[Purchase] Confirmation email failed:', err))
                // }

                // 2. Send User SMS Confirmation (To data recipient as requested)
                if (accountHolderPhone) {
                    await sendOrderSuccessSMS(accountHolderPhone, {
                        network: (pkg as any).network,
                        size: (pkg as any).size,
                        price: priceToCharge,
                        recipientNumber: phoneNumber,
                        currentBalance: newBalance
                    }).then(() => console.log('[Purchase] Confirmation SMS sent successfully'))
                      .catch((err: Error) => console.error('[Purchase] Confirmation SMS failed:', err))
                }

                // 3. Send Admin Agent Alert
                if (isAgent) {
                    await sendAdminAgentOrderAlert()
                        .catch((err: Error) => console.error('[Purchase] Admin agent alert failed:', err))
                }

                // 4. Notify admin via push
                await sendPushToAdmins({
                    title: 'New Data Order',
                    body: `${firstName} · ${(pkg as any).network} ${(pkg as any).size} → ${phoneNumber} (GHS ${priceToCharge.toFixed(2)})`,
                    url: '/admin/orders',
                }).catch(() => {})

                // 4. Trigger Auto-Fulfillment
                // EXPRESS MTN is always manual — skip auto-fulfillment, just alert admin
                if ((pkg as any).network === 'EXPRESS MTN') {
                    await sendAdminNewOrderAlert({
                        referenceCode: (order as any).reference_code,
                        phoneNumber: (order as any).phone_number,
                        network: (order as any).network,
                        size: (order as any).size,
                        price: priceToCharge,
                        customerName: `${firstName} ${(userData as any).last_name || ''}`.trim() || 'Customer',
                        customerEmail: userEmail || 'Unknown',
                        source: 'main_site' as const,
                        reason: 'EXPRESS MTN — Manual fulfillment required'
                    }).catch(err => console.error('[Purchase] EXPRESS MTN admin alert failed:', err))
                } else {
                    await triggerFulfillment((order as any).id, (pkg as any).network, {
                        email: userEmail || 'Unknown',
                        name: `${firstName} ${(userData as any).last_name || ''}`.trim() || 'Customer'
                    })
                }
            }
        } catch (postPurchaseError) {
            console.error('[Purchase] Post-purchase notification/fulfillment failed:', postPurchaseError)
        }

        // Return immediately — don't wait for fulfillment/emails/SMS
        return NextResponse.json({
            success: true,
            order: {
                id: (order as any).id,
                reference_code: referenceCode,
                status: 'pending',
                network: (pkg as any).network,
                size: (pkg as any).size,
                phone_number: phoneNumber,
                price: priceToCharge,
                new_balance: newBalance,
            },
        })
    } catch (error: any) {
        console.error('Purchase error:', error)
        return NextResponse.json({ error: error.message ? `Internal server error: ${error.message}` : 'Internal server error' }, { status: 500 })
    }
}

async function updateCustomerPurchases(
    supabase: any,
    userId: string,
    phoneNumber: string,
    amount: number
) {
    const { data: existing } = await supabase
        .from('customer_purchases')
        .select('*')
        .eq('user_id', userId)
        .eq('customer_phone', phoneNumber)
        .single()

    if (existing) {
        await supabase
            .from('customer_purchases')
            .update({
                total_purchases: existing.total_purchases + 1,
                total_spent: existing.total_spent + amount,
                last_purchase_at: new Date().toISOString(),
            })
            .eq('id', existing.id)
    } else {
        await supabase.from('customer_purchases').insert({
            user_id: userId,
            customer_phone: phoneNumber,
            total_purchases: 1,
            total_spent: amount,
            first_purchase_at: new Date().toISOString(),
            last_purchase_at: new Date().toISOString(),
        })
    }
}

async function triggerFulfillment(orderId: string, network: string, user: { email: string, name: string }) {
    try {
        const { sendAdminNewOrderAlert } = await import('@/lib/email-service')
        const { syncShopOrderStatus } = await import('@/lib/shop-service')
        const supabase = createServerClient()

        const { data: settingsData } = await supabase
            .from('admin_settings')
            .select('key, value')
            .in('key', ['auto_fulfillment_enabled', 'fulfillment_settings'])

        const settingsMap = (settingsData || []).reduce((acc: any, curr: any) => {
            acc[curr.key] = curr.value
            return acc
        }, {})

        const { data: order } = await supabase
            .from('orders')
            .select('*')
            .eq('id', orderId)
            .single()

        if (!order) {
            console.error(`[Fulfillment] Order ${orderId} not found`)
            return
        }

        const alertDetails = {
            referenceCode: (order as any).reference_code,
            phoneNumber: (order as any).phone_number,
            network: (order as any).network,
            size: (order as any).size,
            price: (order as any).price,
            customerName: user.name,
            customerEmail: user.email,
            source: 'main_site' as const,
            reason: ''
        }

        if (String(settingsMap.auto_fulfillment_enabled) === 'false') {
            await sendAdminNewOrderAlert({ ...alertDetails, reason: 'Global auto-fulfillment is disabled' })
                .catch(err => console.error('[Fulfillment] Admin alert (global disabled) failed:', err))
            return
        }

        // ── Parse all supplier network settings ───────────────────────────
        let fulfillmentSettings: {
            networks: Record<string, boolean>
            codecraft_networks: Record<string, boolean>
            kingflexy_networks: Record<string, boolean>
            eazydata_networks: Record<string, boolean>
            agentportal_networks: Record<string, boolean>
        } = { networks: {}, codecraft_networks: {}, kingflexy_networks: {}, eazydata_networks: {}, agentportal_networks: {} }
        try {
            if (settingsMap.fulfillment_settings) {
                const parsed = typeof settingsMap.fulfillment_settings === 'string'
                    ? JSON.parse(settingsMap.fulfillment_settings)
                    : settingsMap.fulfillment_settings
                fulfillmentSettings.networks = parsed.networks || {}
                fulfillmentSettings.codecraft_networks = parsed.codecraft_networks || {}
                fulfillmentSettings.kingflexy_networks = parsed.kingflexy_networks || {}
                fulfillmentSettings.eazydata_networks = parsed.eazydata_networks || {}
                fulfillmentSettings.agentportal_networks = parsed.agentportal_networks || {}
            }
        } catch (e) {
            console.error('[Fulfillment] Failed to parse fulfillment_settings:', e)
        }

        const isDataKazinaEnabled = fulfillmentSettings.networks[network] === true
        const isCodeCraftEnabled = fulfillmentSettings.codecraft_networks[network] === true
        const isKingFlexyEnabled = fulfillmentSettings.kingflexy_networks[network] === true
        const isEazyDataEnabled = fulfillmentSettings.eazydata_networks[network] === true
        const isAgentPortalEnabled = fulfillmentSettings.agentportal_networks[network] === true

        // ── Conflict Guard ─────────────────────────────────────────────────
        const activeSupplierCount = [isDataKazinaEnabled, isCodeCraftEnabled, isKingFlexyEnabled, isEazyDataEnabled, isAgentPortalEnabled].filter(Boolean).length
        if (activeSupplierCount > 1) {
            console.error(`[Fulfillment] CONFLICT DETECTED for ${network} on order ${orderId}`)
            await sendAdminNewOrderAlert({
                ...alertDetails,
                reason: `⚠️ SYSTEM HALTED: Multiple suppliers are active for ${network}. Order ${orderId} kept pending. Fix in admin panel immediately.`
            }).catch(err => console.error('[Fulfillment] Conflict alert failed:', err))
            return
        }

        // ── No Supplier Guard ──────────────────────────────────────────────
        if (!isDataKazinaEnabled && !isCodeCraftEnabled && !isKingFlexyEnabled && !isEazyDataEnabled && !isAgentPortalEnabled) {
            console.log(`[Fulfillment] No active supplier for network ${network}. Order ${orderId} kept pending.`)
            await sendAdminNewOrderAlert({ ...alertDetails, reason: `No active supplier configured for network: ${network}` })
                .catch(err => console.error('[Fulfillment] No-supplier alert failed:', err))
            return
        }

        const supplierLabel = isCodeCraftEnabled ? 'codecraft' : isKingFlexyEnabled ? 'kingflexy' : isEazyDataEnabled ? 'eazydata' : isAgentPortalEnabled ? 'agentportal' : 'datakazina'
        console.log(`[Fulfillment] Routing to ${supplierLabel} for order ${orderId} | network: ${network}`)

        // ── Idempotency check ──────────────────────────────────────────────
        const { data: existingTracking } = await supabase
            .from('mtn_fulfillment_tracking')
            .select('status')
            .eq('order_id', orderId)
            .single()

        if (existingTracking) {
            console.log(`[Fulfillment] Order ${orderId} already in tracking, skipping`)
            return
        }

        // ── Execute fulfillment ────────────────────────────────────────────
        let result: { success: boolean; reference?: string; transactionId?: string; error?: string; apiResponse?: any }
        try {
            if (isCodeCraftEnabled) {
                const { fulfillOrder: ccFulfill } = await import('@/lib/codecraft-service')
                result = await ccFulfill(network, (order as any).phone_number, (order as any).size, orderId)
            } else if (isKingFlexyEnabled) {
                const { fulfillOrder: kfFulfill } = await import('@/lib/kingflexy-service')
                result = await kfFulfill(network, (order as any).phone_number, (order as any).size, orderId)
            } else if (isEazyDataEnabled) {
                const { fulfillOrder: edFulfill } = await import('@/lib/eazydata-service')
                result = await edFulfill(network, (order as any).phone_number, (order as any).size, orderId)
            } else if (isAgentPortalEnabled) {
                const { fulfillOrder: apFulfill } = await import('@/lib/agentportal-service')
                result = await apFulfill(network, (order as any).phone_number, (order as any).size, orderId)
            } else {
                const { fulfillOrder: dkFulfill } = await import('@/lib/fulfillment-service')
                result = await dkFulfill(network, (order as any).phone_number, (order as any).size, orderId)
            }
        } catch (supplierErr: any) {
            console.error(`[Fulfillment] Supplier call exception for order ${orderId}:`, supplierErr)
            await sendAdminNewOrderAlert({ ...alertDetails, reason: `Supplier exception: ${supplierErr.message}` })
                .catch(err => console.error('[Fulfillment] Exception alert failed:', err))
            return
        }

        if (result.success) {
            // ── Build atomic orders update ─────────────────────────────────
            const ordersUpdate: Record<string, any> = {
                status: 'processing',
                updated_at: new Date().toISOString(),
                fulfillment_method: supplierLabel,
            }
            if (isCodeCraftEnabled && (result.transactionId || result.reference)) {
                ordersUpdate.codecraft_reference = result.transactionId || result.reference
            }
            if (isKingFlexyEnabled && (result.transactionId || result.reference)) {
                ordersUpdate.kingflexy_reference = result.transactionId || result.reference
            }
            if (isEazyDataEnabled && (result.transactionId || result.reference)) {
                ordersUpdate.eazydata_reference = result.transactionId || result.reference
            }
            if (isAgentPortalEnabled && (result.transactionId || result.reference)) {
                ordersUpdate.agentportal_reference = result.transactionId || result.reference
            }
            if (!isCodeCraftEnabled && !isKingFlexyEnabled && !isEazyDataEnabled && !isAgentPortalEnabled && (result.transactionId || result.reference)) {
                ordersUpdate.dakazina_reference = result.transactionId || result.reference
            }

            const { error: updateError } = await (supabase.from('orders') as any)
                .update(ordersUpdate)
                .eq('id', orderId)

            if (updateError) {
                console.error(`[OrderPurchase] Failed to update order ${orderId} status:`, updateError.message)
                // If the error is a check-constraint violation on fulfillment_method (migration not yet run),
                // retry without that field so the order is not left stuck as 'pending'.
                if (updateError.message?.includes('fulfillment_method_check') || updateError.code === '23514') {
                    const { fulfillment_method: _drop, ...fallbackUpdate } = ordersUpdate
                    const { error: retryError } = await (supabase.from('orders') as any)
                        .update(fallbackUpdate)
                        .eq('id', orderId)
                    if (retryError) {
                        console.error(`[OrderPurchase] Fallback update also failed for ${orderId}:`, retryError.message)
                    } else {
                        console.warn(`[OrderPurchase] Order ${orderId} marked processing WITHOUT fulfillment_method — run migration 20260528_add_kingflexy_fulfillment_method.sql in Supabase to fix constraint`)
                    }
                }
            }

            await (supabase.from('mtn_fulfillment_tracking') as any).insert({
                order_id: orderId,
                status: 'processing',
                api_response: {
                    ...(result.apiResponse || {}),
                    reference: result.transactionId || result.reference,
                    supplier: supplierLabel,
                    network,
                },
            })

            // Sync status to healing wrapper so shop owners see it
            await syncShopOrderStatus(orderId, 'processing').catch(err =>
                console.error(`[Fulfillment] syncShopOrderStatus failed for ${orderId}:`, err)
            )
        } else {
            // Failure — keep order as pending (do not update orders table status)
            console.warn(`[Fulfillment] Supplier ${supplierLabel} failed for order ${orderId}: ${result.error}`)
            await sendAdminNewOrderAlert({ ...alertDetails, reason: `Auto-fulfillment API error (${supplierLabel}): ${result.error || 'Unknown error'}` })
                .catch(err => console.error('[Fulfillment] Admin alert (API failed) failed:', err))

            await (supabase.from('mtn_fulfillment_tracking') as any).insert({
                order_id: orderId,
                status: 'failed',
                api_response: { error: result.error, supplier: supplierLabel, network, ...result.apiResponse },
            })
        }
    } catch (error) {
        console.error(`[Fulfillment] Error processing order ${orderId}:`, error)
    }
}
